version: '3'

services:

  mariadb_galera:
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 3m # must be higher than SST duration
      placement:
        constraints:
          - node.labels.database == galera
      resources:
        limits:
          memory: 1G
    image: severalnines/mariadb:10.1
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    ports:
      - 3306:3306
    environment:
      CLUSTER_NAME: "MariaDB_Galera"
      DISCOVERY_SERVICE: "192.168.55.111:2379,192.168.55.112:2379,192.168.55.113:2379"
      MYSQL_ROOT_PASSWORD: "mypassword123"
      XTRABACKUP_PASSWORD: "mypassword123"
    command:
      - --innodb_buffer_pool_size=512M
    networks:
      - db_galera_net
    volumes:
      - datadir:/var/lib/mysql
    healthcheck:
      interval: 10s
      retries: 20 # interval * retries > SST duration
    

networks:
  db_galera_net:
    external: true

volumes:
  datadir:
