# multi with replicas
# create network beforehand:
#   $ docker create network galera_net -d overlay

version: '3'

services:

  mariadb_galera:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
      update_config:
        parallelism: 1
        delay: 3m
    image: severalnines/mariadb:10.1
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    ports:
      - "3306:3306"
    environment:
      CLUSTER_NAME: "MariaDB_Galera"
      DISCOVERY_SERVICE: "192.168.55.111:2379,192.168.55.112:2379,192.168.55.207:2379"
      MYSQL_ROOT_PASSWORD: "mypassword123"
      XTRABACKUP_PASSWORD: "mypassword123"
    command: "--innodb-buffer-pool-size=256M --max-connections=51 --wsrep-provider-options=\"gcache.size=64M\""
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - galera_net

networks:
  galera_net:
    external: true
